title: Fandango
email: contacto@civio.es
description: >
  FAke News discovery and propagation from big Data ANalysis 
  and artificial intelliGence Operations
baseurl:
url:

facebook_id: 1555294067917940

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/css
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
